include(":framework:web")
include(":framework:data-jpa")
include(":framework:data-mybatis")
include(":framework:security-core")
include(":framework:security-server")
include(":framework:security-resource")
include(":util:api-sign")
include(":util:excel")
