-- USED IN TESTS THAT USE HSQL
CREATE TABLE OAUTH_CLIENT_DETAILS
(
    CLIENT_ID               VARCHAR PRIMARY KEY,
    RESOURCE_IDS            VARCHAR,
    CLIENT_SECRET           INTEGER default 0,
    SCOPE                   VARCHAR DEFAULT 'a',
    AUTHORIZED_GRANT_TYPES  VARCHAR,
    WEB_SERVER_REDIRECT_URI VARCHAR,
    AUTHORITIES             VARCHAR,
    ACCESS_TOKEN_VALIDITY   INTEGER,
    REFRESH_TOKEN_VALIDITY  INTEGER,
    ADDITIONAL_INFORMATION  VARCHAR,
    AUTOAPPROVE             VARCHAR
);
COMMENT
ON TABLE OAUTH_CLIENT_DETAILS IS '客户端信息';
COMMENT
ON COLUMN OAUTH_CLIENT_DETAILS.CLIENT_ID IS '客户端ID';
COMMENT
ON COLUMN OAUTH_CLIENT_DETAILS.RESOURCE_IDS IS '资源ID';
COMMENT
ON COLUMN OAUTH_CLIENT_DETAILS.CLIENT_SECRET IS '客户端密码';
COMMENT
ON COLUMN OAUTH_CLIENT_DETAILS.SCOPE IS '授权范围';
COMMENT
ON COLUMN OAUTH_CLIENT_DETAILS.AUTHORIZED_GRANT_TYPES IS '授权方式';
COMMENT
ON COLUMN OAUTH_CLIENT_DETAILS.WEB_SERVER_REDIRECT_URI IS '服务器跳转地址';
COMMENT
ON COLUMN OAUTH_CLIENT_DETAILS.AUTHORITIES IS '权限';
COMMENT
ON COLUMN OAUTH_CLIENT_DETAILS.ACCESS_TOKEN_VALIDITY IS '授权TOKEN有效时间';
COMMENT
ON COLUMN OAUTH_CLIENT_DETAILS.REFRESH_TOKEN_VALIDITY IS '刷新TOKEN有效时间';
COMMENT
ON COLUMN OAUTH_CLIENT_DETAILS.ADDITIONAL_INFORMATION IS '附加信息';
COMMENT
ON COLUMN OAUTH_CLIENT_DETAILS.AUTOAPPROVE IS '是否自动批准';

CREATE TABLE OAUTH_CLIENT_TOKEN
(
    TOKEN_ID          VARCHAR unique,
    TOKEN             LONGVARBINARY,
    AUTHENTICATION_ID VARCHAR PRIMARY KEY,
    USER_NAME         VARCHAR,
    CLIENT_ID         VARCHAR
);

COMMENT
ON TABLE OAUTH_CLIENT_TOKEN IS '客户端TOKEN';
COMMENT
ON COLUMN OAUTH_CLIENT_TOKEN.TOKEN_ID IS 'TOKEN ID';
COMMENT
ON COLUMN OAUTH_CLIENT_TOKEN.TOKEN IS 'TOKEN';
COMMENT
ON COLUMN OAUTH_CLIENT_TOKEN.AUTHENTICATION_ID IS '权限信息ID';
COMMENT
ON COLUMN OAUTH_CLIENT_TOKEN.USER_NAME IS '用户名';
COMMENT
ON COLUMN OAUTH_CLIENT_TOKEN.CLIENT_ID IS '客户端ID';
CREATE INDEX IDXNAME ON OAUTH_CLIENT_TOKEN (USER_NAME, TOKEN);

ALTER TABLE OAUTH_CLIENT_TOKEN
    ADD FOREIGN KEY (CLIENT_ID) REFERENCES OAUTH_CLIENT_DETAILS (CLIENT_ID);