PK
FK
UNIQUE
INDEX
IDGENERATOR
SEQUENCE
LOGICALDELETE
ASBOOLEAN

@startuml security

entity api_token {
    api token
    ==
    id : VARCHAR(191) PK NOT NULL -- id
    access_token : VARCHAR(191) UNIQUE NOT NULL -- accessToken
    refresh_token : VARCHAR(191) UNIQUE NOT NULL -- refreshToken
    authentication : BLOB NULL -- authentication
}

@enduml