CREATE TABLE if not exists OAUTH_CLIENT_TOKEN (
  TOKEN_ID VARCHAR unique ,
  TOKEN LONGVARBINARY,
  AUTHENTICATION_ID VARCHAR PRIMARY KEY,
  USER_NAME VARCHAR,
  CLIENT_ID INTEGER
);

COMMENT ON TABLE OAUTH_CLIENT_TOKEN IS '客户端TOKEN';
COMMENT ON COLUMN OAUTH_CLIENT_TOKEN.TOKEN_ID IS 'TOKEN ID';
COMMENT ON COLUMN OAUTH_CLIENT_TOKEN.TOKEN IS 'TOKEN';
COMMENT ON COLUMN OAUTH_CLIENT_TOKEN.AUTHENTICATION_ID IS '权限信息ID';
COMMENT ON COLUMN OAUTH_CLIENT_TOKEN.USER_NAME IS '用户名';
COMMENT ON COLUMN OAUTH_CLIENT_TOKEN.CLIENT_ID IS '客户端ID';