== 接口授权说明

系统通过OAuth2.0授权保护

.客户端信息

* 客户端信息

----
client-id: 0i9wOtG5VGWaUiSL1dvVNT1yT5SojYmj
client-secret: kayXzITUDVrbdDqaY2gJJtuAqs2UXzaFSVJleI8ACs695n3ctmCfqQh35kA93Hu7
----

* 传入方式： 通过 Basic Authentication 方式传入
* 获取/刷新accessToken等接口都必须传入客户端信息
        
[source,http,options="nowrap"]
----
Accept: application/json;version=1.0
Accept-Language: zh-CN,en-US;q=0.5
Accept-Encoding: gzip, deflate
Authorization: Basic MGk5d090RzVWR1dhVWlTTDFkdlZOVDF5VDVTb2pZbWo6a2F5WHpJVFVEVnJiZERxYVkyZ0pKdHVBcXMyVVh6YUZTVkpsZUk4QUNzNjk1bjNjdG1DZnFRaDM1a0E5M0h1Nw===

----

.获取accessToken

* 系统账户获取accessToken接口：/oauth/token；
* 测试账号：root ,密码:123456
* 所有参数都为必填参数

.请求头参数
|====
|名称|类型|是否必填|描述|示例值

| Authorization
| String
| 是
| 授权
| Basic MGk5d090RzVWR1dhVWlTTDFkdlZOVDF5VDVTb2pZbWo6a2F5WHpJVFVEVnJiZERxYVkyZ0pKdHVBcXMyVVh6YUZTVkpsZUk4QUNzNjk1bjNjdG1DZnFRaDM1a0E5M0h1Nw===

|====

.请求参数
|====
|名称|类型|是否必填|描述|默认值|示例值

| grant_type
|String
|是
|授权方式，值域：password，refresh_token
|-
|password

|scope
|String
|是
|权限范围，可定死为：trust
|-
|trust

| username
|String
|是
|账户名
|-
|admin

| password
|String
|是
|密码
|-
|e10adc3949ba59abbe56e057f20f883e
|====

.响应参数
|====
|名称|类型|描述|示例值

| accessToken
|String
|存取令牌
|8f003269-5183-46be-94a9-68748721d323

| token_type
|String
|令牌类型
|bearer

| refresh_token
|String
|刷新令牌
|58a31470-ad9e-4991-96f2-0340250397d9

| expires_in
|Integer
|存取令牌多少时间后过期，单位秒，如：39753秒后过期
|43163

| scope
|String
|权限范围，可定死为：trust
|trust
|====

.响应示例

[source,json]
----
{
  "accessToken" : "8f003269-5183-46be-94a9-68748721d323",
  "token_type" : "bearer",
  "refresh_token" : "58a31470-ad9e-4991-96f2-0340250397d9",
  "expires_in" : 43163,
  "scope" : "trust"
}
----

.刷新accessToken

* accessToken过期时间为首次获取的12小时后，12小时内重新获取不会产生新的token，accessToken过期后可以通过refresh_token重新获取accessToken

TIP: refresh_token过期时间为一个月，refresh_token过期后须重新通过用户密码方式获取。

* 刷新accessToken接口：/oauth/token；
* 所有参数都为必填参数

.请求头参数
|====
|名称|类型|是否必填|描述|示例值

| Authorization
|String
|是
|授权
|Basic MGk5d090RzVWR1dhVWlTTDFkdlZOVDF5VDVTb2pZbWo6a2F5WHpJVFVEVnJiZERxYVkyZ0pKdHVBcXMyVVh6YUZTVkpsZUk4QUNzNjk1bjNjdG1DZnFRaDM1a0E5M0h1Nw===

|====

.请求参数
|====
|名称|类型|是否必填|描述|默认值|示例值

| grant_type
|String
|是
|授权方式，值域：password，refresh_token
|-
|refresh_token

| scope
|String
|是
|权限范围，可定死为：trust
|-
|trust

| refresh_token
|String
|是
|刷新令牌
|-
|58a31470-ad9e-4991-96f2-0340250397d9

|====

.响应参数
|====
|名称|类型|描述|示例值

| accessToken
|String
|存取令牌
|0a377384-82e8-42cf-a44b-45c2733cb79b

| token_type
|String
|令牌类型
|bearer

| refresh_token
|String
|刷新令牌
|58a31470-ad9e-4991-96f2-0340250397d9

| expires_in
|Integer
|存取令牌多少时间后过期，单位秒，如：39753秒后过期
|43199

| scope
|String
|权限范围，可定死为：trust
|trust

|====

.响应示例
[source,json]
----
{
  "accessToken" : "0a377384-82e8-42cf-a44b-45c2733cb79b",
  "token_type" : "bearer",
  "refresh_token" : "58a31470-ad9e-4991-96f2-0340250397d9",
  "expires_in" : 43199,
  "scope" : "trust"
}
----

.accessToken的使用

* 支持header、application/x-www-form-urlencoded等方式传递，推荐使用http headers方式

例子：

[source,http,options="nowrap"]
----
Accept: application/json;version=1.0.b
Accept-Language: zh-CN,en-US;q=0.5
Accept-Encoding: gzip, deflate
Authorization: Bearer c788a252-8f42-4229-943c-0544268e9c65
----

或

----
http://xxxx/orders?accessToken=c788a252-8f42-4229-943c-0544268e9c65
----

TIP: 用户通过授权接口得到accessToken后（即每次登录后），另外调用用户信息接口查看用户信息；授权接口不返回用户信息。


=== 小程序登录流程

[plantuml]
----
@startuml 登录
(*) --> "调用wx.login(Object object)获取登录凭证（code）"
--> "调用服务器后台 13.2 wechat/miniOauth 接口，使用 code 换取 openid 、access_token 和 hasBound 等信息"
if "检查hasBound" then
-->[true] "使用 access_token（刷新token） 调用2.2. 刷新accessToken,获取最新access_token"
--> (*)
else
-->[false] "跳转登录界面"
--> "使用openid，用户输入的手机号、密码，调用后台2.1. 获取accessToken接口，获取access_token"
--> (*)
endif
@enduml
----