@startuml DATABASE

entity OAUTH_CLIENT_TOKEN {
    客户端TOKEN
    ==
    TOKEN_ID : VARCHAR PK NOT NULL -- 主键
    TOKEN : VARCHAR NULL -- TOKEN
    AUTHENTICATION_ID : VARCHAR NULL -- 权限信息ID
    USER_NAME : VARCHAR NULL -- 用户名
    CLIENT_ID : INT NULL -- 客户端ID
}

@enduml
ENGINE
PK
FK
AUTO_INCREMENT
UNIQUE
INDEX
UNSIGNED
NOT
NULL
VERSION
CREATEDDATE
CREATEDBY
LASTMODIFIEDDATE
LASTMODIFIEDBY
LOGICALDELETE
ASBOOLEAN
DEFAULT
SEQUENCE
IDGENERATOR
CODETYPE